/* ============================================================
   Jugnu's voice.

   Prefers warm, pre-recorded ElevenLabs clips under
     /public/voice/<moment>-<idx>.mp3
   (generated by scripts/generate-jugnu-voice.mjs and listed in
   /public/voice/voice-manifest.json). Falls back to the device's
   Hindi speechSynthesis voice for anything not pre-rendered, so
   the app still talks even before clips are generated.

   Everything is SSR-safe (all window access is guarded) and the
   browser autoplay policy is handled with primeAudio(), which the
   app calls from the first real user gesture (sound toggle / enter).
   ============================================================ */

import { useEffect, useState } from 'react';

/* ── pre-recorded clips ─────────────────────────────────────── */

let manifest: Record<string, true> | null = null;
let manifestPromise: Promise<Record<string, true>> | null = null;
let current: HTMLAudioElement | null = null;
let primed = false;

function loadManifest(): Promise<Record<string, true>> {
  if (manifest) return Promise.resolve(manifest);
  if (manifestPromise) return manifestPromise;
  manifestPromise = fetch('/voice/voice-manifest.json')
    .then((r) => (r.ok ? r.json() : {}))
    .then((m: Record<string, true>) => (manifest = m || {}))
    .catch(() => (manifest = {}));
  return manifestPromise;
}

/** A ~1-sample silent WAV, used to unlock HTML audio on first user gesture. */
function silentWav(): string {
  if (typeof window === 'undefined' || typeof btoa === 'undefined') return '';
  const sr = 8000;
  const samples = 1;
  const buf = new ArrayBuffer(44 + samples * 2);
  const dv = new DataView(buf);
  const w = (o: number, s: string) => {
    for (let i = 0; i < s.length; i++) dv.setUint8(o + i, s.charCodeAt(i));
  };
  w(0, 'RIFF');
  dv.setUint32(4, 36 + samples * 2, true);
  w(8, 'WAVE');
  w(12, 'fmt ');
  dv.setUint32(16, 16, true);
  dv.setUint16(20, 1, true);
  dv.setUint16(22, 1, true);
  dv.setUint32(24, sr, true);
  dv.setUint32(28, sr * 2, true);
  dv.setUint16(32, 2, true);
  dv.setUint16(34, 16, true);
  w(36, 'data');
  dv.setUint32(40, samples * 2, true);
  let bin = '';
  const bytes = new Uint8Array(buf);
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return 'data:audio/wav;base64,' + btoa(bin);
}

/**
 * Unlock HTML audio under the browser autoplay policy. Jugnu speaks from a
 * mount effect — i.e. outside a direct tap — so iOS Safari / Chrome would
 * otherwise block audio.play() and the voice goes silent. Call this from the
 * first real user gesture (enabling sound, entering the app). Idempotent.
 */
export function primeAudio(): void {
  if (primed || typeof window === 'undefined') return;
  primed = true;
  try {
    const a = new Audio(silentWav());
    a.volume = 0;
    const p = a.play();
    if (p && typeof p.then === 'function') p.then(() => { try { a.pause(); } catch { /* */ } }).catch(() => {});
  } catch {
    /* no-op */
  }
  void loadManifest();
  try {
    window.speechSynthesis?.getVoices();
  } catch {
    /* no-op */
  }
}

function stopCurrent(): void {
  if (current) {
    try {
      current.onerror = null;
      current.pause();
      current.src = '';
    } catch {
      /* no-op */
    }
    current = null;
  }
}

/**
 * Play the pre-recorded clip for a moment if it exists, otherwise speak the
 * Hindi line via the device voice. `idx` selects the rotated variant.
 */
export function playMoment(key: string, idx: number, fallbackHi: string, on: boolean): void {
  if (!on || typeof window === 'undefined') return;
  stopCurrent();
  try {
    window.speechSynthesis?.cancel();
  } catch {
    /* no-op */
  }
  void loadManifest().then((m) => {
    const id = `${key}-${idx}`;
    if (!m[id]) {
      speak(fallbackHi, on);
      return;
    }
    let audio: HTMLAudioElement;
    try {
      audio = new Audio(`/voice/${id}.mp3`);
    } catch {
      speak(fallbackHi, on);
      return;
    }
    audio.volume = 0.95;
    audio.onerror = () => {
      if (current !== audio) return; // stale handler
      speak(fallbackHi, on);
    };
    audio.play().catch(() => {
      if (current !== audio) return; // stale handler
      speak(fallbackHi, on);
    });
    current = audio;
  });
}

/* ── device TTS fallback ────────────────────────────────────── */

export function speak(text: string, on: boolean): void {
  if (!on || typeof window === 'undefined' || !('speechSynthesis' in window) || !text) return;
  try {
    window.speechSynthesis.cancel();
    const u = new SpeechSynthesisUtterance(text);
    u.lang = 'hi-IN';
    u.rate = 0.95;
    u.pitch = 1.22; // a touch higher → warmer, younger
    const vs = window.speechSynthesis.getVoices();
    const hi =
      vs.find((v) => /hi[-_]IN/i.test(v.lang) && /female|woman|lekha|veena|swara|kalpana|google/i.test(v.name)) ||
      vs.find((v) => /hi[-_]IN/i.test(v.lang)) ||
      vs.find((v) => /hi/i.test(v.lang));
    if (hi) u.voice = hi;
    window.speechSynthesis.speak(u);
  } catch {
    /* no-op */
  }
}

export function stopSpeak(): void {
  stopCurrent();
  try {
    window.speechSynthesis?.cancel();
  } catch {
    /* no-op */
  }
}

/* ── typewriter hook ────────────────────────────────────────── */

/** Reveals `text` one char at a time; returns [shown, done]. */
export function useTypewriter(text: string, on = true, speed = 26): [string, boolean] {
  const [out, setOut] = useState(on ? '' : text);
  const [done, setDone] = useState(!on);
  useEffect(() => {
    if (!on) {
      setOut(text);
      setDone(true);
      return;
    }
    setOut('');
    setDone(false);
    let i = 0;
    const id = setInterval(() => {
      i++;
      setOut(text.slice(0, i));
      if (i >= text.length) {
        clearInterval(id);
        setDone(true);
      }
    }, speed);
    return () => clearInterval(id);
  }, [text, on, speed]);
  return [out, done];
}
